name: Extract OnePlus OPS Firmware

on:
  workflow_dispatch:
    inputs:
      ops_firmware_url:
        description: 'URL of the firmware ZIP file (containing the .ops file)'
        required: true
        type: string
      output_directory:
        description: 'Directory to store extracted files (e.g., extracted_firmware)'
        required: false
        default: 'extracted_firmware'
        type: string

jobs:
  extract_firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone oppo_decrypt tool
        run: |
          git clone https://github.com/bkerler/oppo_decrypt.git
          cd oppo_decrypt
          pip3 install -r requirements.txt

      - name: Download Firmware ZIP
        run: |
          curl -L -o firmware.zip "${{ github.event.inputs.ops_firmware_url }}"

      - name: Unzip Firmware Archive
        run: |
          mkdir temp_firmware_unzip
          unzip firmware.zip -d temp_firmware_unzip/
          echo "Contents of temp_firmware_unzip:"
          ls -R temp_firmware_unzip/

      - name: Find and Extract OPS firmware
        run: |
          OPS_FILE=$(find temp_firmware_unzip/ -name "*.ops" -print -quit)

          if [ -z "$OPS_FILE" ]; then
              echo "ERROR: No .ops file found in the unzipped archive!"
              exit 1
          fi

          echo "Found OPS file: $OPS_FILE"

          python3 oppo_decrypt/opscrypto.py decrypt "$OPS_FILE" --extractdir="${{ github.event.inputs.output_directory }}"

      - name: Upload extracted artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extracted-firmware-${{ github.run_id }}
          path: ${{ github.event.inputs.output_directory }}
          retention-days: 7

      - name: Clean up temporary files (Optional)
        run: |
          rm firmware.zip
          rm -rf temp_firmware_unzip/
