name: Extract OnePlus OPS Firmware

on:
  workflow_dispatch:
    inputs:
      ops_firmware_url:
        description: 'URL of the firmware ZIP file (containing the .ops file)'
        required: true
        type: string
      output_directory:
        description: 'Directory to store extracted files (e.g., extracted_firmware)'
        required: false
        default: 'extracted_firmware'
        type: string

jobs:
  extract_firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout firmware extraction repository
        uses: actions/checkout@v4
        with:
          path: workflow_repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone oppo_decrypt tool
        run: |
          git clone https://github.com/bkerler/oppo_decrypt.git
          cd oppo_decrypt
          pip3 install -r requirements.txt

      - name: Download Firmware ZIP
        run: |
          curl -L -o firmware.zip "${{ github.event.inputs.ops_firmware_url }}"

      - name: Unzip Firmware Archive
        run: |
          mkdir -p temp_firmware_unzip
          unzip -o firmware.zip -d temp_firmware_unzip/
          echo "Contents of temp_firmware_unzip:"
          ls -R temp_firmware_unzip/

      - name: Find and Extract OPS firmware
        id: extract_ops_step
        run: |
          OPS_FILE=$(find temp_firmware_unzip/ -name "*.ops" -print -quit)

          if [ -z "$OPS_FILE" ]; then
              echo "ERROR: No .ops file found in the unzipped archive!"
              exit 1
          fi

          echo "Found OPS file: $OPS_FILE"

          python3 oppo_decrypt/opscrypto.py decrypt "$OPS_FILE" --extractdir="${{ github.workspace }}/${{ github.event.inputs.output_directory }}"
          echo "extracted_output_path=${{ github.workspace }}/${{ github.event.inputs.output_directory }}" >> $GITHUB_OUTPUT

      # --- START: New Steps for GitHub Release ---
      - name: Generate Release Tag
        id: generate_tag
        run: |
          # Change to the repository directory to ensure git commands work correctly
          cd Porting_repo
          # Generate a dynamic tag based on the current date and run ID
          RELEASE_TAG="op1-release-$(date +%Y%m%d%H%M%S)-${GITHUB_RUN_ID}"
          echo "Generated Release Tag: $RELEASE_TAG"
          # Set the tag as an output for subsequent steps
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          # Configure git for tagging (if not already done by previous steps)
          git config user.name "github-actions[bot]"
          git config user.email "41899989+github-actions[bot]@users.noreply.github.com"
          # Create and push the tag to the repository
          git tag "$RELEASE_TAG"
          git push origin "$RELEASE_TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.release_tag }} # Use the tag generated in the previous step
          release_name: Release ${{ steps.generate_tag.outputs.release_tag }}
          body: |
            Automatic release of op1.img from firmware extraction workflow.
            This release was triggered by a workflow_dispatch event.
            Workflow Run ID: ${{ github.run_id }}
          draft: false # Set to true if you want to manually publish later
          prerelease: false # Set to true if this is a pre-release

      - name: Upload op1.img to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # URL provided by the create_release step
          asset_path: Porting_repo/op1.img # The path to the op1.img file within the Porting_repo workspace
          asset_name: op1.img # The name for the file on the release
          asset_content_type: application/octet-stream # Standard content type for a binary file

      - name: Clean up temporary files (Optional)
        run: |
          rm firmware.zip
          rm -rf temp_firmware_unzip/
          rm -rf workflow_repo/
          rm -rf Porting_repo/
